apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-deployment
    labels:
        app: webapp
spec:
    replicas: 3
    selector:
        matchLabels:
            app: webapp
    template:
        metadata:
            labels: 
                app: webapp
        spec:
            containers:
            - name: webapp
              image: bijoyashis/demo:v1
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
    name: webapp-service
    labels:
        app: webapp
spec:
    selector:
        app: webapp
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
    type: LoadBalancer

