---
- hosts: kubernetes
  become: true
  user: ec2-user
  tasks:
  - name: Install Docker
    command: yum install docker -y
  - name: Start Docker Service
    command: service docker start
  - name: Start Kubernetes Service
    command: kubectl apply -f /opt/Ansible/Ansible/kube-deploy.yml
