---
- hosts: dev
  become: true
  tasks:
  - name: Start container
    docker_container:
      name: demo
      image: "bijoyashis/demo:{DOCKER_TAG}"
      state: started
      published_ports:
          - 0.0.0.0:8080:8080
